---
name: jellyfin-plugin-trailerpreview
guid: a1b2c3d4-e5f6-7890-abcd-ef1234567890
version: 1.0.0
jellyfin_version: 10.10.0
nicename: Trailer Preview
description: Display movie and TV show trailers in a Netflix-style overlay when hovering over items
overview: >
  A modern, elegant solution for previewing trailers by hovering over movies and TV shows.
  Features include customizable timing, positioning, size controls, background effects,
  audio settings, and multi-platform support for Web, Desktop, Mobile, and TV clients.
category: General
owner: Ziifkah
artifacts:
  - Jellyfin.Plugin.TrailerPreview.dll
build_type: dotnet
dotnet_configuration: Release
dotnet_framework: net8.0
